/**
 * Structured validation codes for the Decision Validation Guardian.
 * Fail-closed release uses CRITICAL / HIGH; others are advisory.
 */

export const GUARDIAN_VALIDATION_CODES = [
  "DOCUMENT_UNREADABLE",
  "DOCUMENT_INVALID",
  "DOCUMENT_INSUFFICIENT_TEXT",
  "CANONICAL_NON_REQUIREMENT",
  "CANONICAL_QA_META",
  "CANONICAL_HEADING",
  "CANONICAL_EVALUATION_LEAK",
  "CANONICAL_DEADLINE_AS_REQUIREMENT",
  "REQUIREMENT_TRUNCATED",
  "REQUIREMENT_ID_LOST",
  "REQUIREMENT_CONDITION_LOST",
  "REQUIREMENT_PROVENANCE_WRONG",
  "REQUIREMENT_SEMANTIC_MISMATCH",
  "DUPLICATE_SEMANTIC_IDENTITY",
  "CONDITIONAL_PROMOTED_TO_MANDATORY",
  "DEADLINE_TIME_MUTATED",
  "DEADLINE_TIMEZONE_LOST",
  "COUNT_DRIFT",
  "CROSS_MODULE_ID_MISMATCH",
  "ACTION_CANONICAL_MISMATCH",
  "VERIFICATION_MARKED_BLOCKING",
  "DECISION_NO_BID_WITHOUT_BLOCKER",
  "DECISION_BID_WITH_UNRESOLVED_MANDATORY",
  "DECISION_AI_OVERRIDE",
  "FIT_INCONSISTENCY",
  "REPORT_DATASET_MISMATCH",
  "GUARDIAN_INTERNAL_ERROR",
  // Prompt 2 — evidence / source / derived-field integrity
  "EVIDENCE_MISSING_FOR_CONFIRMED_FIT",
  "EVIDENCE_MISSING_FOR_CONFIRMED_GAP",
  "VERIFICATION_ESCALATED_TO_HIGH_RISK",
  "HIGH_RISK_FACT_MUTATED",
  "HIGH_RISK_FACT_UNSUPPORTED",
  "SOURCE_CONTRADICTION",
  "EXTERNAL_OVERWRITE_TENDER_FACT",
  "EXTERNAL_CLAIM_UNGROUNDED",
  "DERIVED_FIELD_CONTRADICTS_CANONICAL",
  "STALE_RESULT_MISMATCH",
  "UNSUPPORTED_AI_CLAIM",
  "MISSING_COMMERCIAL_OBLIGATION",
  "REVIEWER_SCENARIO_LEAK",
] as const;

export type GuardianValidationCode = (typeof GUARDIAN_VALIDATION_CODES)[number];

export type GuardianSeverity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";

/** Severities that block analysis release (fail-closed). */
export const BLOCKING_SEVERITIES = new Set<GuardianSeverity>(["CRITICAL", "HIGH"]);
