import { scoreKeyword, type KeywordEntry, type ScoreInput } from "./types";

type Draft = Omit<KeywordEntry, "priority" | "searchVolume"> & {
  scores: ScoreInput;
};

function entry(draft: Draft): KeywordEntry {
  return {
    ...draft,
    priority: scoreKeyword(draft.scores),
    searchVolume: "UNKNOWN",
  };
}

/**
 * Machine-readable keyword registry — single source of truth for SEO/GEO expansion.
 * Native terminology per language (not mechanical EN translations).
 */
export const keywordRegistry: KeywordEntry[] = [
  // ——— EN company intelligence ———
  entry({
    id: "en-ci-primary",
    keyword: "company intelligence platform",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "primary",
    capability: "company_intelligence",
    topic: "company_intelligence",
    targetUrl: "/solutions/company-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "capability_cluster + category framing",
    confidence: "high",
    demandEvidence: "web_category_presence",
    scores: { commercialIntent: 8, relevance: 10, demandEvidenceStrength: 4, competition: 7, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 7 },
  }),
  entry({
    id: "en-ci-best",
    keyword: "best company intelligence platform",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "commercial",
    capability: "company_intelligence",
    topic: "company_intelligence",
    targetUrl: "/guides/company-readiness-software",
    contentType: "guide",
    status: "mapped",
    source: "commercial_intent_template",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 9, relevance: 9, demandEvidenceStrength: 2, competition: 8, conversionPotential: 8, contentOpportunity: 7, geographicOpportunity: 6 },
  }),
  entry({
    id: "en-ci-q",
    keyword: "What is the best company intelligence platform?",
    language: "en",
    region: "GLOBAL",
    intent: "question",
    kind: "ai_conversational",
    capability: "company_intelligence",
    topic: "company_intelligence",
    targetUrl: "/solutions/company-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "geo_question_set",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 10, demandEvidenceStrength: 2, competition: 6, conversionPotential: 7, contentOpportunity: 9, geographicOpportunity: 7 },
  }),
  entry({
    id: "en-profile",
    keyword: "company profile management software",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "secondary",
    capability: "company_intelligence",
    topic: "company_profile",
    targetUrl: "/solutions/company-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "capability_cluster",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 6, conversionPotential: 7, contentOpportunity: 7, geographicOpportunity: 6 },
  }),

  // ——— EN document compliance ———
  entry({
    id: "en-dc-primary",
    keyword: "document compliance software",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "primary",
    capability: "document_compliance",
    topic: "document_compliance",
    targetUrl: "/solutions/document-compliance",
    contentType: "solution",
    status: "mapped",
    source: "capability_cluster + web_category_presence",
    confidence: "high",
    demandEvidence: "web_category_presence",
    scores: { commercialIntent: 9, relevance: 10, demandEvidenceStrength: 7, competition: 8, conversionPotential: 9, contentOpportunity: 8, geographicOpportunity: 8 },
  }),
  entry({
    id: "en-dc-expiry",
    keyword: "business document expiry tracking",
    language: "en",
    region: "GLOBAL",
    intent: "problem",
    kind: "problem",
    capability: "document_compliance",
    topic: "document_expiry",
    targetUrl: "/guides/manage-expiring-certificates",
    contentType: "guide",
    status: "mapped",
    source: "capability_cluster",
    confidence: "high",
    demandEvidence: "web_category_presence",
    scores: { commercialIntent: 8, relevance: 10, demandEvidenceStrength: 6, competition: 5, conversionPotential: 9, contentOpportunity: 9, geographicOpportunity: 7 },
  }),
  entry({
    id: "en-dc-how",
    keyword: "How can a company track compliance documents?",
    language: "en",
    region: "GLOBAL",
    intent: "question",
    kind: "ai_conversational",
    capability: "document_compliance",
    topic: "document_compliance",
    targetUrl: "/guides/track-compliance-documents",
    contentType: "guide",
    status: "mapped",
    source: "geo_question_set",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 10, demandEvidenceStrength: 2, competition: 4, conversionPotential: 8, contentOpportunity: 9, geographicOpportunity: 7 },
  }),
  entry({
    id: "en-dc-cert",
    keyword: "How can businesses manage expiring certificates?",
    language: "en",
    region: "GLOBAL",
    intent: "question",
    kind: "question",
    capability: "document_compliance",
    topic: "certificate_expiry",
    targetUrl: "/guides/manage-expiring-certificates",
    contentType: "guide",
    status: "mapped",
    source: "geo_question_set",
    confidence: "high",
    demandEvidence: "web_category_presence",
    scores: { commercialIntent: 7, relevance: 10, demandEvidenceStrength: 6, competition: 5, conversionPotential: 9, contentOpportunity: 9, geographicOpportunity: 8 },
  }),
  entry({
    id: "en-dc-sheets",
    keyword: "alternative to spreadsheets for supplier compliance",
    language: "en",
    region: "GLOBAL",
    intent: "comparison",
    kind: "comparison",
    capability: "document_compliance",
    topic: "spreadsheet_alternative",
    targetUrl: "/compare/spreadsheets",
    contentType: "compare",
    status: "mapped",
    source: "competitor_category",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 8, relevance: 9, demandEvidenceStrength: 3, competition: 5, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 6 },
  }),

  // ——— EN supplier qualification ———
  entry({
    id: "en-sq-primary",
    keyword: "supplier qualification software",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "primary",
    capability: "supplier_qualification",
    topic: "supplier_qualification",
    targetUrl: "/solutions/supplier-qualification",
    contentType: "solution",
    status: "mapped",
    source: "capability_cluster + web_category_presence",
    confidence: "high",
    demandEvidence: "web_category_presence",
    scores: { commercialIntent: 9, relevance: 10, demandEvidenceStrength: 8, competition: 8, conversionPotential: 9, contentOpportunity: 8, geographicOpportunity: 8 },
  }),
  entry({
    id: "en-sq-best",
    keyword: "best software for supplier qualification",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "commercial",
    capability: "supplier_qualification",
    topic: "supplier_qualification",
    targetUrl: "/solutions/supplier-qualification",
    contentType: "solution",
    status: "mapped",
    source: "commercial_intent_template",
    confidence: "high",
    demandEvidence: "web_category_presence",
    scores: { commercialIntent: 10, relevance: 10, demandEvidenceStrength: 7, competition: 8, conversionPotential: 9, contentOpportunity: 8, geographicOpportunity: 7 },
  }),
  entry({
    id: "en-sq-q",
    keyword: "What is the best software for supplier qualification?",
    language: "en",
    region: "GLOBAL",
    intent: "question",
    kind: "ai_conversational",
    capability: "supplier_qualification",
    topic: "supplier_qualification",
    targetUrl: "/solutions/supplier-qualification",
    contentType: "solution",
    status: "mapped",
    source: "geo_question_set",
    confidence: "high",
    demandEvidence: "web_category_presence",
    scores: { commercialIntent: 9, relevance: 10, demandEvidenceStrength: 7, competition: 7, conversionPotential: 8, contentOpportunity: 9, geographicOpportunity: 7 },
  }),
  entry({
    id: "en-sq-mgmt",
    keyword: "best supplier management software",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "commercial",
    capability: "supplier_qualification",
    topic: "supplier_management_category",
    targetUrl: "/compare/supplier-management-tools",
    contentType: "compare",
    status: "mapped",
    source: "adjacent_category",
    confidence: "medium",
    demandEvidence: "web_category_presence",
    notes: "Buyer SRM suites dominate; Bidvera is supplier-side readiness — comparison page explains fit honestly.",
    scores: { commercialIntent: 9, relevance: 6, demandEvidenceStrength: 7, competition: 9, conversionPotential: 5, contentOpportunity: 7, geographicOpportunity: 7 },
  }),

  // ——— EN evidence / questionnaires / decisions / opportunity ———
  entry({
    id: "en-ev-org",
    keyword: "How can companies organize business evidence?",
    language: "en",
    region: "GLOBAL",
    intent: "question",
    kind: "ai_conversational",
    capability: "evidence_intelligence",
    topic: "evidence",
    targetUrl: "/guides/organize-business-evidence",
    contentType: "guide",
    status: "mapped",
    source: "geo_question_set",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 10, demandEvidenceStrength: 2, competition: 4, conversionPotential: 8, contentOpportunity: 9, geographicOpportunity: 6 },
  }),
  entry({
    id: "en-qa",
    keyword: "software for supplier questionnaires",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "commercial",
    capability: "client_requests_questionnaires",
    topic: "questionnaires",
    targetUrl: "/solutions/client-requests-questionnaires",
    contentType: "solution",
    status: "mapped",
    source: "capability_cluster",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 8, relevance: 10, demandEvidenceStrength: 3, competition: 6, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 6 },
  }),
  entry({
    id: "en-qa-how",
    keyword: "How can suppliers respond to questionnaires?",
    language: "en",
    region: "GLOBAL",
    intent: "question",
    kind: "question",
    capability: "client_requests_questionnaires",
    topic: "questionnaires",
    targetUrl: "/guides/respond-to-client-questionnaires",
    contentType: "guide",
    status: "mapped",
    source: "geo_question_set",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 10, demandEvidenceStrength: 2, competition: 4, conversionPotential: 8, contentOpportunity: 9, geographicOpportunity: 6 },
  }),
  entry({
    id: "en-dec",
    keyword: "bid no-bid decision support software",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "primary",
    capability: "decision_intelligence",
    topic: "bid_no_bid",
    targetUrl: "/solutions/decision-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "capability_cluster",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 8, relevance: 10, demandEvidenceStrength: 3, competition: 6, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 6 },
  }),
  entry({
    id: "en-ready",
    keyword: "What software helps companies stay procurement-ready?",
    language: "en",
    region: "GLOBAL",
    intent: "question",
    kind: "ai_conversational",
    capability: "opportunity_readiness",
    topic: "procurement_readiness",
    targetUrl: "/solutions/opportunity-readiness",
    contentType: "solution",
    status: "mapped",
    source: "geo_question_set",
    confidence: "high",
    demandEvidence: "unknown",
    notes: "Opportunity readiness via requests/calendar/analysis — not Matching Engine.",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 6, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 6 },
  }),
  entry({
    id: "en-opp-disc",
    keyword: "How can companies discover relevant opportunities?",
    language: "en",
    region: "GLOBAL",
    intent: "question",
    kind: "question",
    capability: "opportunity_readiness",
    topic: "opportunity_organization",
    targetUrl: "/solutions/opportunity-readiness",
    contentType: "solution",
    status: "mapped",
    source: "geo_question_set",
    confidence: "medium",
    demandEvidence: "unknown",
    notes: "Answer must not claim public tender discovery feed / Matching Engine.",
    scores: { commercialIntent: 6, relevance: 7, demandEvidenceStrength: 2, competition: 7, conversionPotential: 5, contentOpportunity: 7, geographicOpportunity: 6 },
  }),
  entry({
    id: "en-sme",
    keyword: "How can SMEs manage business opportunities?",
    language: "en",
    region: "GLOBAL",
    intent: "question",
    kind: "ai_conversational",
    capability: "opportunity_readiness",
    topic: "sme",
    targetUrl: "/use-cases/sme-suppliers",
    contentType: "use_case",
    status: "mapped",
    source: "geo_question_set",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 5, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 7 },
  }),
  entry({
    id: "en-ta",
    keyword: "tender analysis software",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "secondary",
    capability: "tender_analysis",
    topic: "tender_analysis",
    targetUrl: "/solutions/decision-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "capability_cluster",
    confidence: "high",
    demandEvidence: "unknown",
    notes: "Positioned as one capability inside decision intelligence — not primary brand identity.",
    scores: { commercialIntent: 8, relevance: 8, demandEvidenceStrength: 3, competition: 7, conversionPotential: 7, contentOpportunity: 6, geographicOpportunity: 6 },
  }),
  entry({
    id: "en-cal",
    keyword: "tender deadline calendar software",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "long_tail",
    capability: "tender_calendar",
    topic: "tender_calendar",
    targetUrl: "/solutions/opportunity-readiness",
    contentType: "solution",
    status: "covered_by_hub",
    source: "capability_cluster",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 9, demandEvidenceStrength: 2, competition: 4, conversionPotential: 6, contentOpportunity: 7, geographicOpportunity: 5 },
  }),

  // ——— FR native ———
  entry({
    id: "fr-conf",
    keyword: "logiciel conformité documents entreprise",
    language: "fr",
    region: "FR",
    intent: "commercial",
    kind: "primary",
    capability: "document_compliance",
    topic: "document_compliance",
    targetUrl: "/solutions/document-compliance",
    contentType: "solution",
    status: "mapped",
    source: "native_vendor_terminology",
    confidence: "high",
    demandEvidence: "native_vendor_terminology",
    scores: { commercialIntent: 9, relevance: 10, demandEvidenceStrength: 7, competition: 7, conversionPotential: 9, contentOpportunity: 8, geographicOpportunity: 9 },
  }),
  entry({
    id: "fr-vigilance",
    keyword: "suivi expiration attestations fournisseurs",
    language: "fr",
    region: "FR",
    intent: "problem",
    kind: "problem",
    capability: "document_compliance",
    topic: "document_expiry",
    targetUrl: "/guides/manage-expiring-certificates",
    contentType: "guide",
    status: "mapped",
    source: "native_vendor_terminology (Kontractis/Aprovall/Fournissio)",
    confidence: "high",
    demandEvidence: "native_vendor_terminology",
    notes: "FR market often frames buyer vigilance; Bidvera fit is supplier-side readiness/docs.",
    scores: { commercialIntent: 8, relevance: 7, demandEvidenceStrength: 8, competition: 7, conversionPotential: 6, contentOpportunity: 7, geographicOpportunity: 9 },
  }),
  entry({
    id: "fr-qualif",
    keyword: "logiciel qualification fournisseur",
    language: "fr",
    region: "FR",
    intent: "commercial",
    kind: "primary",
    capability: "supplier_qualification",
    topic: "supplier_qualification",
    targetUrl: "/solutions/supplier-qualification",
    contentType: "solution",
    status: "mapped",
    source: "native_vendor_terminology",
    confidence: "high",
    demandEvidence: "native_vendor_terminology",
    scores: { commercialIntent: 9, relevance: 9, demandEvidenceStrength: 7, competition: 8, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 9 },
  }),
  entry({
    id: "fr-q",
    keyword: "Quel logiciel pour suivre les documents de conformité d’une entreprise ?",
    language: "fr",
    region: "FR",
    intent: "question",
    kind: "ai_conversational",
    capability: "document_compliance",
    topic: "document_compliance",
    targetUrl: "/guides/track-compliance-documents",
    contentType: "guide",
    status: "mapped",
    source: "geo_question_set_native",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 10, demandEvidenceStrength: 2, competition: 5, conversionPotential: 8, contentOpportunity: 9, geographicOpportunity: 9 },
  }),
  entry({
    id: "fr-intel",
    keyword: "plateforme d’intelligence d’entreprise",
    language: "fr",
    region: "FR",
    intent: "commercial",
    kind: "primary",
    capability: "company_intelligence",
    topic: "company_intelligence",
    targetUrl: "/solutions/company-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 10, demandEvidenceStrength: 2, competition: 6, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),
  entry({
    id: "fr-ao",
    keyword: "aide à la décision soumissionner ou non",
    language: "fr",
    region: "FR",
    intent: "commercial",
    kind: "long_tail",
    capability: "decision_intelligence",
    topic: "bid_no_bid",
    targetUrl: "/solutions/decision-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 5, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),

  // ——— ES native ———
  entry({
    id: "es-calif",
    keyword: "software calificación de proveedores",
    language: "es",
    region: "ES-LATAM",
    intent: "commercial",
    kind: "primary",
    capability: "supplier_qualification",
    topic: "supplier_qualification",
    targetUrl: "/solutions/supplier-qualification",
    contentType: "solution",
    status: "mapped",
    source: "native_vendor_terminology",
    confidence: "high",
    demandEvidence: "native_vendor_terminology",
    scores: { commercialIntent: 9, relevance: 10, demandEvidenceStrength: 7, competition: 7, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 9 },
  }),
  entry({
    id: "es-cumpl",
    keyword: "software gestión cumplimiento documentos",
    language: "es",
    region: "ES-LATAM",
    intent: "commercial",
    kind: "primary",
    capability: "document_compliance",
    topic: "document_compliance",
    targetUrl: "/solutions/document-compliance",
    contentType: "solution",
    status: "mapped",
    source: "native_vendor_terminology",
    confidence: "high",
    demandEvidence: "native_vendor_terminology",
    scores: { commercialIntent: 9, relevance: 10, demandEvidenceStrength: 7, competition: 7, conversionPotential: 9, contentOpportunity: 8, geographicOpportunity: 9 },
  }),
  entry({
    id: "es-caduc",
    keyword: "alertas caducidad certificados empresa",
    language: "es",
    region: "ES-LATAM",
    intent: "problem",
    kind: "problem",
    capability: "document_compliance",
    topic: "document_expiry",
    targetUrl: "/guides/manage-expiring-certificates",
    contentType: "guide",
    status: "mapped",
    source: "native_vendor_terminology",
    confidence: "high",
    demandEvidence: "native_vendor_terminology",
    scores: { commercialIntent: 8, relevance: 10, demandEvidenceStrength: 7, competition: 5, conversionPotential: 9, contentOpportunity: 8, geographicOpportunity: 8 },
  }),
  entry({
    id: "es-q",
    keyword: "¿Cómo puede una empresa controlar documentos de cumplimiento?",
    language: "es",
    region: "ES-LATAM",
    intent: "question",
    kind: "ai_conversational",
    capability: "document_compliance",
    topic: "document_compliance",
    targetUrl: "/guides/track-compliance-documents",
    contentType: "guide",
    status: "mapped",
    source: "geo_question_set_native",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 10, demandEvidenceStrength: 2, competition: 4, conversionPotential: 8, contentOpportunity: 9, geographicOpportunity: 8 },
  }),
  entry({
    id: "es-intel",
    keyword: "plataforma de inteligencia empresarial para proveedores",
    language: "es",
    region: "ES-LATAM",
    intent: "commercial",
    kind: "secondary",
    capability: "company_intelligence",
    topic: "company_intelligence",
    targetUrl: "/solutions/company-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 6, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),

  // ——— AR native ———
  entry({
    id: "ar-taheel",
    keyword: "برنامج تأهيل الموردين",
    language: "ar",
    region: "MENA",
    intent: "commercial",
    kind: "primary",
    capability: "supplier_qualification",
    topic: "supplier_qualification",
    targetUrl: "/solutions/supplier-qualification",
    contentType: "solution",
    status: "mapped",
    source: "native_vendor_terminology",
    confidence: "high",
    demandEvidence: "native_vendor_terminology",
    scores: { commercialIntent: 9, relevance: 9, demandEvidenceStrength: 7, competition: 7, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 9 },
  }),
  entry({
    id: "ar-docs",
    keyword: "إدارة وثائق الامتثال للشركات",
    language: "ar",
    region: "MENA",
    intent: "commercial",
    kind: "primary",
    capability: "document_compliance",
    topic: "document_compliance",
    targetUrl: "/solutions/document-compliance",
    contentType: "solution",
    status: "mapped",
    source: "native_vendor_terminology",
    confidence: "high",
    demandEvidence: "native_vendor_terminology",
    scores: { commercialIntent: 9, relevance: 10, demandEvidenceStrength: 6, competition: 6, conversionPotential: 9, contentOpportunity: 8, geographicOpportunity: 9 },
  }),
  entry({
    id: "ar-q",
    keyword: "كيف تتابع الشركة مستندات الامتثال وتواريخ انتهائها؟",
    language: "ar",
    region: "MENA",
    intent: "question",
    kind: "ai_conversational",
    capability: "document_compliance",
    topic: "document_expiry",
    targetUrl: "/guides/track-compliance-documents",
    contentType: "guide",
    status: "mapped",
    source: "geo_question_set_native",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 10, demandEvidenceStrength: 2, competition: 4, conversionPotential: 8, contentOpportunity: 9, geographicOpportunity: 9 },
  }),
  entry({
    id: "ar-intel",
    keyword: "منصة ذكاء الشركة للموردين",
    language: "ar",
    region: "MENA",
    intent: "commercial",
    kind: "secondary",
    capability: "company_intelligence",
    topic: "company_intelligence",
    targetUrl: "/solutions/company-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 10, demandEvidenceStrength: 2, competition: 5, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),

  // ——— ZH native ———
  entry({
    id: "zh-zizhi",
    keyword: "供应商资质管理软件",
    language: "zh",
    region: "CN",
    intent: "commercial",
    kind: "primary",
    capability: "supplier_qualification",
    topic: "supplier_qualification",
    targetUrl: "/solutions/supplier-qualification",
    contentType: "solution",
    status: "mapped",
    source: "native_vendor_terminology",
    confidence: "high",
    demandEvidence: "native_vendor_terminology",
    scores: { commercialIntent: 9, relevance: 9, demandEvidenceStrength: 8, competition: 8, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 9 },
  }),
  entry({
    id: "zh-expiry",
    keyword: "企业资质到期提醒",
    language: "zh",
    region: "CN",
    intent: "problem",
    kind: "problem",
    capability: "document_compliance",
    topic: "document_expiry",
    targetUrl: "/guides/manage-expiring-certificates",
    contentType: "guide",
    status: "mapped",
    source: "native_vendor_terminology (简道云/轻流)",
    confidence: "high",
    demandEvidence: "native_vendor_terminology",
    scores: { commercialIntent: 8, relevance: 10, demandEvidenceStrength: 8, competition: 7, conversionPotential: 9, contentOpportunity: 8, geographicOpportunity: 9 },
  }),
  entry({
    id: "zh-hegui",
    keyword: "企业合规文件管理软件",
    language: "zh",
    region: "CN",
    intent: "commercial",
    kind: "primary",
    capability: "document_compliance",
    topic: "document_compliance",
    targetUrl: "/solutions/document-compliance",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "high",
    demandEvidence: "native_vendor_terminology",
    scores: { commercialIntent: 8, relevance: 10, demandEvidenceStrength: 6, competition: 7, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 9 },
  }),
  entry({
    id: "zh-q",
    keyword: "企业如何跟踪合规文件和证书到期？",
    language: "zh",
    region: "CN",
    intent: "question",
    kind: "ai_conversational",
    capability: "document_compliance",
    topic: "document_expiry",
    targetUrl: "/guides/track-compliance-documents",
    contentType: "guide",
    status: "mapped",
    source: "geo_question_set_native",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 10, demandEvidenceStrength: 2, competition: 5, conversionPotential: 8, contentOpportunity: 9, geographicOpportunity: 9 },
  }),
  entry({
    id: "zh-intel",
    keyword: "企业情报与就绪度平台",
    language: "zh",
    region: "CN",
    intent: "commercial",
    kind: "secondary",
    capability: "company_intelligence",
    topic: "company_intelligence",
    targetUrl: "/solutions/company-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 10, demandEvidenceStrength: 2, competition: 5, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),

  // ——— EN supporting capabilities ———
  entry({
    id: "en-workflow",
    keyword: "team bid decision workflow software",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "long_tail",
    capability: "team_workflow",
    topic: "team_workflow",
    targetUrl: "/solutions/decision-intelligence",
    contentType: "solution",
    status: "covered_by_hub",
    source: "capability_cluster",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 5, conversionPotential: 7, contentOpportunity: 7, geographicOpportunity: 6 },
  }),
  entry({
    id: "en-alerts",
    keyword: "smart alerts for tender deadlines",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "long_tail",
    capability: "smart_alerts",
    topic: "smart_alerts",
    targetUrl: "/solutions/opportunity-readiness",
    contentType: "solution",
    status: "covered_by_hub",
    source: "capability_cluster",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 8, demandEvidenceStrength: 2, competition: 5, conversionPotential: 6, contentOpportunity: 6, geographicOpportunity: 5 },
  }),
  entry({
    id: "en-memory",
    keyword: "decision memory for bid decisions",
    language: "en",
    region: "GLOBAL",
    intent: "informational",
    kind: "secondary",
    capability: "decision_memory",
    topic: "decision_memory",
    targetUrl: "/solutions/decision-intelligence",
    contentType: "solution",
    status: "covered_by_hub",
    source: "capability_cluster",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 5, relevance: 9, demandEvidenceStrength: 1, competition: 4, conversionPotential: 6, contentOpportunity: 7, geographicOpportunity: 5 },
  }),
  entry({
    id: "en-explainable",
    keyword: "explainable bid no-bid software",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "commercial",
    capability: "explainable_decision",
    topic: "explainable_decision",
    targetUrl: "/solutions/decision-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "capability_cluster",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 8, relevance: 10, demandEvidenceStrength: 2, competition: 5, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 6 },
  }),
  entry({
    id: "en-pdf",
    keyword: "export bid decision PDF report",
    language: "en",
    region: "GLOBAL",
    intent: "informational",
    kind: "long_tail",
    capability: "pdf_export",
    topic: "pdf_export",
    targetUrl: "/solutions/decision-intelligence",
    contentType: "solution",
    status: "covered_by_hub",
    source: "capability_cluster",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 4, relevance: 8, demandEvidenceStrength: 1, competition: 3, conversionPotential: 5, contentOpportunity: 5, geographicOpportunity: 4 },
  }),
  entry({
    id: "en-action-plan",
    keyword: "tender action plan software",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "secondary",
    capability: "action_plan",
    topic: "action_plan",
    targetUrl: "/solutions/decision-intelligence",
    contentType: "solution",
    status: "covered_by_hub",
    source: "capability_cluster",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 8, demandEvidenceStrength: 2, competition: 5, conversionPotential: 6, contentOpportunity: 6, geographicOpportunity: 5 },
  }),
  entry({
    id: "en-evidence-sw",
    keyword: "business evidence management software",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "primary",
    capability: "evidence_intelligence",
    topic: "evidence",
    targetUrl: "/solutions/evidence-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "capability_cluster",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 8, relevance: 10, demandEvidenceStrength: 3, competition: 6, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 6 },
  }),
  entry({
    id: "en-how-automate-docs",
    keyword: "how to automate compliance document tracking",
    language: "en",
    region: "GLOBAL",
    intent: "problem",
    kind: "problem",
    capability: "document_compliance",
    topic: "document_compliance",
    targetUrl: "/guides/track-compliance-documents",
    contentType: "guide",
    status: "mapped",
    source: "commercial_intent_template",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 6, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 6 },
  }),
  entry({
    id: "en-proc-alt",
    keyword: "procurement readiness software for suppliers",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "commercial",
    capability: "platform_general",
    topic: "procurement_readiness",
    targetUrl: "/compare/procurement-software",
    contentType: "compare",
    status: "mapped",
    source: "adjacent_category",
    confidence: "medium",
    demandEvidence: "web_category_presence",
    notes: "Adjacent to buyer procurement suites; Bidvera is supplier-side readiness.",
    scores: { commercialIntent: 8, relevance: 7, demandEvidenceStrength: 5, competition: 8, conversionPotential: 6, contentOpportunity: 7, geographicOpportunity: 7 },
  }),
  entry({
    id: "en-dms-alt",
    keyword: "document management alternative for supplier certificates",
    language: "en",
    region: "GLOBAL",
    intent: "comparison",
    kind: "comparison",
    capability: "document_compliance",
    topic: "dms_alternative",
    targetUrl: "/compare/document-management-systems",
    contentType: "compare",
    status: "mapped",
    source: "competitor_category",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 8, demandEvidenceStrength: 3, competition: 7, conversionPotential: 6, contentOpportunity: 7, geographicOpportunity: 6 },
  }),

  // ——— FR extended ———
  entry({
    id: "fr-preuves",
    keyword: "logiciel gestion des preuves entreprise",
    language: "fr",
    region: "FR",
    intent: "commercial",
    kind: "secondary",
    capability: "evidence_intelligence",
    topic: "evidence",
    targetUrl: "/solutions/evidence-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 5, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),
  entry({
    id: "fr-questionnaire",
    keyword: "assistant questionnaire fournisseur",
    language: "fr",
    region: "FR",
    intent: "commercial",
    kind: "commercial",
    capability: "client_requests_questionnaires",
    topic: "questionnaires",
    targetUrl: "/solutions/client-requests-questionnaires",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 5, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),
  entry({
    id: "fr-prep",
    keyword: "Comment rester prêt pour les demandes acheteurs ?",
    language: "fr",
    region: "FR",
    intent: "question",
    kind: "ai_conversational",
    capability: "opportunity_readiness",
    topic: "procurement_readiness",
    targetUrl: "/solutions/opportunity-readiness",
    contentType: "solution",
    status: "mapped",
    source: "geo_question_set_native",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 9, demandEvidenceStrength: 2, competition: 5, conversionPotential: 7, contentOpportunity: 9, geographicOpportunity: 9 },
  }),
  entry({
    id: "fr-vs-excel",
    keyword: "alternative à Excel pour conformité fournisseur",
    language: "fr",
    region: "FR",
    intent: "comparison",
    kind: "comparison",
    capability: "document_compliance",
    topic: "spreadsheet_alternative",
    targetUrl: "/compare/spreadsheets",
    contentType: "compare",
    status: "mapped",
    source: "competitor_category_native",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 8, relevance: 9, demandEvidenceStrength: 3, competition: 5, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 9 },
  }),

  // ——— ES extended ———
  entry({
    id: "es-evid",
    keyword: "software organización de evidencias empresariales",
    language: "es",
    region: "ES-LATAM",
    intent: "commercial",
    kind: "secondary",
    capability: "evidence_intelligence",
    topic: "evidence",
    targetUrl: "/solutions/evidence-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 5, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),
  entry({
    id: "es-cuest",
    keyword: "cómo responder cuestionarios de clientes proveedores",
    language: "es",
    region: "ES-LATAM",
    intent: "question",
    kind: "question",
    capability: "client_requests_questionnaires",
    topic: "questionnaires",
    targetUrl: "/guides/respond-to-client-questionnaires",
    contentType: "guide",
    status: "mapped",
    source: "geo_question_set_native",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 10, demandEvidenceStrength: 2, competition: 4, conversionPotential: 8, contentOpportunity: 9, geographicOpportunity: 8 },
  }),
  entry({
    id: "es-decision",
    keyword: "software decisión ofertar o no ofertar",
    language: "es",
    region: "ES-LATAM",
    intent: "commercial",
    kind: "long_tail",
    capability: "decision_intelligence",
    topic: "bid_no_bid",
    targetUrl: "/solutions/decision-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 5, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),
  entry({
    id: "es-vs-excel",
    keyword: "alternativa a hojas de cálculo para certificados",
    language: "es",
    region: "ES-LATAM",
    intent: "comparison",
    kind: "comparison",
    capability: "document_compliance",
    topic: "spreadsheet_alternative",
    targetUrl: "/compare/spreadsheets",
    contentType: "compare",
    status: "mapped",
    source: "competitor_category_native",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 8, relevance: 9, demandEvidenceStrength: 3, competition: 5, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 8 },
  }),

  // ——— AR extended ———
  entry({
    id: "ar-evidence",
    keyword: "برنامج تنظيم أدلة الأعمال للشركات",
    language: "ar",
    region: "MENA",
    intent: "commercial",
    kind: "secondary",
    capability: "evidence_intelligence",
    topic: "evidence",
    targetUrl: "/solutions/evidence-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 4, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),
  entry({
    id: "ar-quest",
    keyword: "كيف يرد الموردون على استبيانات العملاء؟",
    language: "ar",
    region: "MENA",
    intent: "question",
    kind: "ai_conversational",
    capability: "client_requests_questionnaires",
    topic: "questionnaires",
    targetUrl: "/guides/respond-to-client-questionnaires",
    contentType: "guide",
    status: "mapped",
    source: "geo_question_set_native",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 10, demandEvidenceStrength: 2, competition: 4, conversionPotential: 8, contentOpportunity: 9, geographicOpportunity: 9 },
  }),
  entry({
    id: "ar-decision",
    keyword: "برنامج دعم قرار التقديم أو عدم التقديم",
    language: "ar",
    region: "MENA",
    intent: "commercial",
    kind: "long_tail",
    capability: "decision_intelligence",
    topic: "bid_no_bid",
    targetUrl: "/solutions/decision-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 4, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),
  entry({
    id: "ar-ready",
    keyword: "كيف تبقى الشركة جاهزة لطلبات المشتريات؟",
    language: "ar",
    region: "MENA",
    intent: "question",
    kind: "ai_conversational",
    capability: "opportunity_readiness",
    topic: "procurement_readiness",
    targetUrl: "/solutions/opportunity-readiness",
    contentType: "solution",
    status: "mapped",
    source: "geo_question_set_native",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 9, demandEvidenceStrength: 2, competition: 4, conversionPotential: 7, contentOpportunity: 9, geographicOpportunity: 9 },
  }),

  // ——— ZH extended ———
  entry({
    id: "zh-evidence",
    keyword: "企业业务证据管理软件",
    language: "zh",
    region: "CN",
    intent: "commercial",
    kind: "secondary",
    capability: "evidence_intelligence",
    topic: "evidence",
    targetUrl: "/solutions/evidence-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 5, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),
  entry({
    id: "zh-quest",
    keyword: "供应商如何高效回复客户问卷？",
    language: "zh",
    region: "CN",
    intent: "question",
    kind: "ai_conversational",
    capability: "client_requests_questionnaires",
    topic: "questionnaires",
    targetUrl: "/guides/respond-to-client-questionnaires",
    contentType: "guide",
    status: "mapped",
    source: "geo_question_set_native",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 6, relevance: 10, demandEvidenceStrength: 2, competition: 4, conversionPotential: 8, contentOpportunity: 9, geographicOpportunity: 9 },
  }),
  entry({
    id: "zh-decision",
    keyword: "投标决策支持软件 投还是不投",
    language: "zh",
    region: "CN",
    intent: "commercial",
    kind: "long_tail",
    capability: "decision_intelligence",
    topic: "bid_no_bid",
    targetUrl: "/solutions/decision-intelligence",
    contentType: "solution",
    status: "mapped",
    source: "native_framing",
    confidence: "medium",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 5, conversionPotential: 7, contentOpportunity: 8, geographicOpportunity: 8 },
  }),
  entry({
    id: "zh-ready",
    keyword: "中小企业如何管理商机与采购就绪度？",
    language: "zh",
    region: "CN",
    intent: "question",
    kind: "ai_conversational",
    capability: "opportunity_readiness",
    topic: "sme",
    targetUrl: "/use-cases/sme-suppliers",
    contentType: "use_case",
    status: "mapped",
    source: "geo_question_set_native",
    confidence: "high",
    demandEvidence: "unknown",
    scores: { commercialIntent: 7, relevance: 9, demandEvidenceStrength: 2, competition: 5, conversionPotential: 8, contentOpportunity: 9, geographicOpportunity: 9 },
  }),
  entry({
    id: "zh-vs-excel",
    keyword: "替代表格管理企业证书到期",
    language: "zh",
    region: "CN",
    intent: "comparison",
    kind: "comparison",
    capability: "document_compliance",
    topic: "spreadsheet_alternative",
    targetUrl: "/compare/spreadsheets",
    contentType: "compare",
    status: "mapped",
    source: "competitor_category_native",
    confidence: "high",
    demandEvidence: "native_vendor_terminology",
    scores: { commercialIntent: 8, relevance: 9, demandEvidenceStrength: 6, competition: 5, conversionPotential: 8, contentOpportunity: 8, geographicOpportunity: 9 },
  }),

  // ——— OFF feature guard ———
  entry({
    id: "en-matching-blocked",
    keyword: "B2B opportunity matching software",
    language: "en",
    region: "GLOBAL",
    intent: "commercial",
    kind: "commercial",
    capability: "opportunity_readiness",
    topic: "matching_engine",
    targetUrl: "/solutions/opportunity-readiness",
    contentType: "solution",
    status: "blocked_off_feature",
    source: "entitlement_catalog commerciallyAvailable:false",
    confidence: "high",
    demandEvidence: "unknown",
    notes: "Do not market Matching Engine as available; map intent to opportunity readiness (requests/calendar) only.",
    scores: { commercialIntent: 8, relevance: 4, demandEvidenceStrength: 2, competition: 8, conversionPotential: 2, contentOpportunity: 3, geographicOpportunity: 5 },
  }),
];
