import { getDictionary } from "@/i18n/dictionaries";
import type { Locale } from "@/i18n/config";
import { defaultLocale } from "@/i18n/config";

export type PdfReportLabels = {
  documentTitle: string;
  decisionReport: string;
  preparedFor: string;
  client: string;
  deadline: string;
  analyzed: string;
  reportDate: string;
  executiveSummary: string;
  decision: string;
  recommendation: string;
  companyTenderFit: string;
  confidence: string;
  bidScore: string;
  tenderReadiness: string;
  whyTitle: string;
  overall: string;
  requirements: string;
  complianceMatrix: string;
  ready: string;
  missing: string;
  verify: string;
  notApplicable: string;
  mandatory: string;
  optional: string;
  missingRequirements: string;
  verificationItems: string;
  evidenceVerificationTitle: string;
  evidence: string;
  risks: string;
  missingDocuments: string;
  nextActions: string;
  clarifications: string;
  sources: string;
  historicalTitle: string;
  pageOf: string;
  confidential: string;
  none: string;
  notAvailable: string;
  status: string;
  source: string;
  nextStep: string;
  positive: string;
  negative: string;
  disclaimer: string;
  historicalEmpty: string;
  dimension: string;
  score: string;
  tableStatus: string;
  tableRequirement: string;
  tableType: string;
  tableSource: string;
  overview: string;
};

/** English defaults — used when locale is en or dictionary key missing. */
const EN: PdfReportLabels = {
  documentTitle: "Bidvera Decision Report",
  decisionReport: "Decision Report",
  preparedFor: "Prepared for",
  client: "Client",
  deadline: "Deadline",
  analyzed: "Analyzed",
  reportDate: "Report date",
  executiveSummary: "Executive Summary",
  decision: "Decision",
  recommendation: "Recommendation",
  companyTenderFit: "Company–Tender Fit",
  confidence: "Confidence",
  bidScore: "Bid Score",
  tenderReadiness: "Tender Readiness",
  whyTitle: "Why this recommendation",
  overall: "Overall",
  requirements: "Requirements",
  complianceMatrix: "Compliance Matrix",
  ready: "Ready",
  missing: "Missing",
  verify: "Verify",
  notApplicable: "Not applicable",
  mandatory: "Mandatory",
  optional: "Optional",
  missingRequirements: "Missing requirements",
  verificationItems: "Verification items",
  evidenceVerificationTitle: "Evidence & verification",
  evidence: "Evidence",
  risks: "Risks",
  missingDocuments: "Missing documents",
  nextActions: "Recommended next actions",
  clarifications: "Clarification questions",
  sources: "Sources",
  historicalTitle: "Relevant historical intelligence",
  pageOf: "Page {page} of {total}",
  confidential: "Confidential — for authorized recipients only",
  none: "None",
  notAvailable: "Not available",
  status: "Status",
  source: "Source",
  nextStep: "Next step",
  positive: "Positive",
  negative: "Negative",
  disclaimer:
    "Generated by Bidvera from the canonical tender analysis. Historical intelligence is an additional signal only — never a guarantee.",
  historicalEmpty: "No verified historical pattern applies to this opportunity yet.",
  dimension: "Dimension",
  score: "Score",
  tableStatus: "Status",
  tableRequirement: "Requirement",
  tableType: "Type",
  tableSource: "Source",
  overview: "Overview",
};

export function getPdfReportLabels(locale: Locale = defaultLocale): PdfReportLabels {
  if (locale === "en") return EN;
  const t = getDictionary(locale).app.report;
  return {
    ...EN,
    decisionReport: t.title,
    client: t.unknownClient === "Unknown client" ? EN.client : EN.client,
    deadline: t.deadline,
    analyzed: t.analyzed,
    recommendation: t.recommendation,
    companyTenderFit: t.companyTenderFit,
    confidence: t.confidence,
    bidScore: t.bidScore,
    tenderReadiness: t.tenderReadiness,
    whyTitle: t.whyTitle,
    overall: t.overall,
    requirements: t.requirements,
    complianceMatrix: t.complianceMatrix,
    ready: t.ready,
    missing: t.missing,
    verify: t.verify,
    notApplicable: t.notApplicable,
    mandatory: t.mandatory,
    optional: t.optional,
    missingRequirements: t.missingRequirements,
    verificationItems: t.verificationItems,
    evidenceVerificationTitle: t.evidenceVerificationTitle,
    evidence: t.evidence,
    risks: t.risks,
    missingDocuments: t.missingDocuments,
    nextActions: t.nextActions,
    clarifications: t.clarifications,
    historicalTitle: t.historicalTitle,
    nextStep: t.nextStep.replace(/:$/, ""),
    positive: t.positive,
    negative: t.negative,
    source: t.source.replace(/:$/, ""),
    none: t.noRisks.includes("No ") ? EN.none : EN.none,
    historicalEmpty: t.historicalEmpty,
  };
}
