-- AlterEnum: email-change audit actions
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EMAIL_CHANGE_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EMAIL_CHANGE_CANCELLED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EMAIL_CHANGE_CONFIRMED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EMAIL_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EMAIL_CHANGE_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACCOUNT_PROFILE_UPDATED';
